# Copyright (c) 2018 CA. All rights reserved.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

version: '3.4'
services:
  gateway-dev:
    hostname: gw-test.day.apim.ca.com
    image: caapim/gateway:9.4.00
    ports:
    - "8081:8080"
    - "8444:8443"
    - "8000:8000"
    volumes:
    - /opt/SecureSpan/Gateway/node/default/etc/bootstrap/services/restman
    - ./deployment/build/gateway/deployment-1.0.0.gw7:/opt/docker/rc.d/deployment.gw7
    #- ./AWS-SK/src/main/gateway/config/global-env.properties:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/global-env.properties
    - ./Enterprise/src/main/gateway/config/global-env.properties:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/global-env.properties
    - ./Enterprise/src/main/gateway/config/privateKeys:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/env/config/privateKeys
    # - ./Enterprise/src/main/gateway/config/certificates:/opt/SecureSpan/Gateway/node/default/etc/bootstrap/certificates
    secrets:
    - source: license
      target: /opt/SecureSpan/Gateway/node/default/etc/bootstrap/license/license.xml
    environment:
      ACCEPT_LICENSE: "true"
      SSG_ADMIN_USERNAME: "admin"
      SSG_ADMIN_PASSWORD: "7layer"
      ENV.PRIVATE_KEY.ssl: '{ "keystore": "Generic", "algorithm": "RSA", "keyPassword": "7layer" }'
      ENV.CERTIFICATE.gw_test.client: '{
                      "verifyHostname" : false,
                      "trustedForSsl" : true,
                      "trustedAsSamlAttestingEntity" : true,
                      "trustAnchor" : true,
                      "revocationCheckingEnabled" : true,
                      "trustedForSigningClientCerts" : true,
                      "trustedForSigningServerCerts" : true,
                      "trustedAsSamlIssuer" : true
                      }'
      ENV.CERTIFICATE_FILE.gw_test.client.pem: |-
                        Bag Attributes
                            friendlyName: ssl
                            localKeyID: 1D 66 77 20 0F C1 32 AC 7A 26 64 CF F9 0E 00 96 28 5C B0 BF 
                        subject=/C=us/ST=MN/L=Minneapolis/CN=gw-test.day.apim.ca.com/emailAddress=aric.day@broadcom.com
                        issuer=/C=us/ST=MN/L=Minneapolis/CN=gw-test.day.apim.ca.com/emailAddress=aric.day@broadcom.com
                        -----BEGIN CERTIFICATE-----
                        MIIDbDCCAlQCCQCd+I9eEtCQMDANBgkqhkiG9w0BAQsFADB4MQswCQYDVQQGEwJ1
                        czELMAkGA1UECAwCTU4xFDASBgNVBAcMC01pbm5lYXBvbGlzMSAwHgYDVQQDDBdn
                        dy10ZXN0LmRheS5hcGltLmNhLmNvbTEkMCIGCSqGSIb3DQEJARYVYXJpYy5kYXlA
                        YnJvYWRjb20uY29tMB4XDTE5MTAzMDE0Mjg1MFoXDTI5MTAyNzE0Mjg1MFoweDEL
                        MAkGA1UEBhMCdXMxCzAJBgNVBAgMAk1OMRQwEgYDVQQHDAtNaW5uZWFwb2xpczEg
                        MB4GA1UEAwwXZ3ctdGVzdC5kYXkuYXBpbS5jYS5jb20xJDAiBgkqhkiG9w0BCQEW
                        FWFyaWMuZGF5QGJyb2FkY29tLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
                        AQoCggEBALYb15y9iHV2M0jtc5cRO6zE3vQC7efFkgZ9zZM9qzhGyZXPcUITRgzC
                        N820bNxTAU9r7xbInSUq4x+ajJMHid6V3Gmi0ZzETyH1gdhrNS9OKRrnhNztqWc0
                        mqi/kNCVpv8QjxTKTWF5I0+UXI3+DQJmISs7Rgs8VHljBkAHVBYu8CIav5bx63KN
                        UQWmH7yQxUFIvl3IaQauaD68QfUXao+J6W46jhYzk9x3/pHUT5mw40SqqqcTXHWw
                        FQx9ZGsZ3tIvUFxX80POgzKfpT0MQZSW4EL+rVqn1zoYftJelk8tRqYqf4RlxAG2
                        YrreGcfB/iUhzlrffzcs9MsTr+xywfcCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
                        II2LkQs+/hNcFciMWxyJ1EyIPAG59uHr4DDX/mfwzuw7//2HCcLFRhCmM+AwSx6O
                        P7eHhWB4ktuwBnwOvvRFZSquXKZJNLFC7RroPRgcmjJEj6tGii3kumiOoHcp3CFD
                        ob83f4OIfbnvLLNpxXLgGefQUrW/j0AYyuN7wojuPJe7cBbaHqlNb1XstJVGfxCq
                        nkSJB8gIokVdBwF9oIj1NmZfw/KdRBxst9hVjaNdE4YUUOwrHdT7Kyt5aargzqku
                        ZuBqjCuyOg8etrBdwCOExo/AuPs1exBL8Kw9wrCPMIVzGem/SiUs/d4oUi7KAuXg
                        /aZpuw1xK0q2ZwGKUmFHRQ==
                        -----END CERTIFICATE-----

secrets:
  license:
    file: ./docker/license.xml
